# Generated by Django 4.2.3 on 2023-07-13 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jobs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ETLFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.PositiveBigIntegerField()),
                ('job_title', models.CharField(max_length=500)),
                ('organisation_id', models.CharField(max_length=500)),
                ('organisation_name', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
                ('remote_work_allowed', models.BooleanField()),
                ('workplace_type', models.CharField(max_length=500)),
                ('date_posted', jobs.models.PSTDateTimeField()),
                ('source_domain', models.CharField(max_length=500)),
                ('easy_apply', models.BooleanField()),
                ('linkedin_link', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='UserJobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hide', models.BooleanField(default=False)),
                ('applied', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, default=None, max_length=5000, null=True)),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
