# Generated by Django 4.2.3 on 2023-07-14 18:44

from django.db import migrations
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_posted',
            field=jobs.models.PSTDateTimeField(blank=True, null=True),
        ),
    ]
