# Generated by Django 4.2.3 on 2023-07-22 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_list_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='user',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='List',
        ),
    ]
