# Generated by Django 4.2.3 on 2023-07-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_list_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjobposting',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
