# Generated by Django 4.2.3 on 2023-07-25 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_list_jobnote_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserJobPosting',
        ),
    ]
