# Generated by Django 4.2.3 on 2023-07-25 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_delete_userjobposting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_id',
            new_name='linkedin_id',
        ),
    ]
