# Generated by Django 4.2.3 on 2023-09-07 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_rename_job_id_job_linkedin_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_id', models.PositiveBigIntegerField()),
                ('location', models.CharField(max_length=500)),
                ('linkedin_link', models.CharField(max_length=5000)),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
        ),
    ]
