# Generated by Django 4.2.3 on 2023-07-24 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0007_jobnote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userjobposting',
            name='archived',
        ),
        migrations.AlterField(
            model_name='jobnote',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
        migrations.AlterField(
            model_name='list',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userjobposting',
            name='job_posting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
    ]
