# Generated by Django 4.2.3 on 2023-09-11 03:44

from django.db import migrations
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_joblocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='date_posted',
        ),
        migrations.AddField(
            model_name='joblocation',
            name='date_posted',
            field=jobs.models.PSTDateTimeField(blank=True, null=True),
        ),
    ]
