# Generated by Django 4.2.3 on 2023-09-15 19:26

from django.db import migrations, models
import django.utils.timezone
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_remove_job_linkedin_id_remove_job_linkedin_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberOfJobsAdded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', jobs.models.PSTDateTimeField(default=django.utils.timezone.now)),
                ('number_of_new_jobs', models.IntegerField(default=None)),
            ],
        ),
    ]
