# Generated by Django 4.2.3 on 2023-09-15 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_numberofjobsadded'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NumberOfJobsAdded',
            new_name='DailyStat',
        ),
        migrations.CreateModel(
            name='JobLocationDailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.dailystat')),
                ('job_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.joblocation')),
            ],
        ),
    ]
