# Generated by Django 4.2.3 on 2023-09-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_rename_numberofjobsadded_dailystat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystat',
            name='number_of_new_jobs',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
