# Generated by Django 4.2.3 on 2023-09-16 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_alter_dailystat_number_of_new_jobs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='organisation_name',
            new_name='company_name',
        ),
        migrations.RemoveField(
            model_name='job',
            name='organisation_id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='source_domain',
        ),
        migrations.RemoveField(
            model_name='job',
            name='workplace_type',
        ),
        migrations.AddField(
            model_name='dailystat',
            name='number_of_new_job_locations',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='ExportRunTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(max_length=500)),
                ('run_time_seconds', models.PositiveBigIntegerField()),
                ('daily_stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.dailystat')),
            ],
        ),
    ]
