# Generated by Django 4.2.3 on 2023-09-18 13:27

from django.db import migrations
import django.utils.timezone
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_rename_organisation_name_job_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystat',
            name='earliest_date_for_new_job_location',
            field=jobs.models.PSTDateTimeField(default=django.utils.timezone.now),
        ),
    ]
