# Generated by Django 4.2.3 on 2023-09-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_dailystat_earliest_date_for_new_job_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystat',
            name='number_of_inbox_jobs_applied',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='dailystat',
            name='number_of_inbox_jobs_closed',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
