# Generated by Django 4.2.3 on 2023-09-19 03:17

from django.db import migrations
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_dailystat_number_of_inbox_jobs_applied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_added',
            field=jobs.models.PSTDateTimeField(default=None, null=True),
        ),
    ]
