# Generated by Django 4.2.3 on 2023-09-19 03:20

from django.db import migrations
import django.utils.timezone
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_item_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=jobs.models.PSTDateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
