# Generated by Django 4.2.3 on 2023-09-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_alter_item_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailystat',
            name='number_of_inbox_jobs_applied',
        ),
        migrations.RemoveField(
            model_name='dailystat',
            name='number_of_inbox_jobs_closed',
        ),
        migrations.AddField(
            model_name='dailystat',
            name='number_of_existing_inbox_jobs_applied',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='dailystat',
            name='number_of_existing_inbox_jobs_closed',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='dailystat',
            name='number_of_new_inbox_jobs_applied',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='dailystat',
            name='number_of_new_inbox_jobs_closed',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
