# Generated by Django 4.2.3 on 2023-09-21 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_remove_dailystat_number_of_inbox_jobs_applied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblocation',
            name='experience_level',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
