# Generated by Django 4.2.3 on 2023-10-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_joblocation_experience_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joblocation',
            old_name='linkedin_id',
            new_name='job_board_id',
        ),
        migrations.RenameField(
            model_name='joblocation',
            old_name='linkedin_link',
            new_name='job_board_link',
        ),
        migrations.AddField(
            model_name='joblocation',
            name='job_board',
            field=models.CharField(default='LinkedIn', max_length=500),
        ),
    ]
