# Generated by Django 4.2.3 on 2023-10-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_joblocation_job_board_id_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblocation',
            name='job_board_id_str',
            field=models.CharField(blank=True, default=None, max_length=500),
        ),
    ]
