# Generated by Django 4.2.3 on 2023-10-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_joblocation_job_board_id_str'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblocation',
            name='job_board_id_str',
        ),
        migrations.AlterField(
            model_name='joblocation',
            name='job_board_id',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
