# Generated by Django 4.2.3 on 2023-10-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_remove_joblocation_job_board_id_str_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblocation',
            name='job_board',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
