# Generated by Django 4.2.3 on 2023-10-14 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0025_joblocation_easy_apply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='easy_apply',
        ),
    ]
