# Generated by Django 4.2.3 on 2023-10-17 13:42

from django.db import migrations, models
import django.db.models.deletion
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0026_remove_job_easy_apply'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobLocationDatePosted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', jobs.models.PSTDateTimeField(blank=True, null=True)),
                ('job_location_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.joblocation')),
            ],
        ),
    ]
