# Generated by Django 4.2.3 on 2023-10-18 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0027_joblocationdateposted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblocation',
            name='date_posted',
        ),
    ]
