# Generated by Django 4.2.3 on 2023-10-25 14:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0028_remove_joblocation_date_posted'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='JobItem',
        ),
        migrations.CreateModel(
            name='JobLocationDatePostedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', jobs.models.PSTDateTimeField(default=django.utils.timezone.now, null=True)),
                ('job_location_date_posted', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.joblocationdateposted')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.list')),
            ],
        ),
    ]
