# Generated by Django 4.2.3 on 2023-10-25 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0029_rename_item_jobitem_joblocationdateposteditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobitem',
            name='job',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
    ]
