# Generated by Django 4.2.3 on 2023-11-02 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0030_alter_jobitem_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joblocationdateposteditem',
            old_name='date_added',
            new_name='date_applied_or_closed',
        ),
    ]
