# Generated by Django 4.2.3 on 2023-11-02 20:03

from django.db import migrations
import django.utils.timezone
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0031_rename_date_added_joblocationdateposteditem_date_adde1d'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblocationdateposteditem',
            name='date_created',
            field=jobs.models.PSTDateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='joblocationdateposteditem',
            name='date_applied_or_closed',
            field=jobs.models.PSTDateTimeField(default=None, null=True),
        ),
    ]
